# Generated by Django 3.2.20 on 2024-01-26 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celery_monitor', '0002_workerstate_last_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskstate',
            name='periodic_task_name',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='periodic_task_name'),
        ),
    ]
